"""Metrics API schemas with strong typing."""

from datetime import datetime

from pydantic import BaseModel, ConfigDict, Field


class PlannerMetrics(BaseModel):
    """Planner performance and reliability metrics."""

    total_plans_generated: int = Field(default=0, ge=0, description="Total plans generated across all planners")
    llm_plans: int = Field(default=0, ge=0, description="Plans generated by LLM planner")
    pattern_plans: int = Field(default=0, ge=0, description="Plans generated by pattern-based fallback")
    cached_plans: int = Field(default=0, ge=0, description="Plans served from cache")
    fallback_rate: float = Field(default=0.0, ge=0.0, le=1.0, description="Rate of LLM failures requiring fallback")
    avg_tokens_per_plan: float = Field(default=0.0, ge=0.0, description="Average tokens used per LLM plan")
    avg_latency_ms: float = Field(default=0.0, ge=0.0, description="Average planning latency in milliseconds")
    cache_hit_rate: float = Field(default=0.0, ge=0.0, le=1.0, description="Cache hit rate (0.0 to 1.0)")

    model_config = ConfigDict(
        validate_assignment=True,
        use_enum_values=False,
        strict=True,
        extra="forbid",
        json_schema_extra={
            "example": {
                "total_plans_generated": 150,
                "llm_plans": 120,
                "pattern_plans": 20,
                "cached_plans": 10,
                "fallback_rate": 0.133,
                "avg_tokens_per_plan": 250.5,
                "avg_latency_ms": 450.2,
                "cache_hit_rate": 0.067,
            }
        },
    )


class RunsByStatusMetrics(BaseModel):
    """Run count by status."""

    pending: int = Field(ge=0, description="Number of pending runs")
    running: int = Field(ge=0, description="Number of running runs")
    completed: int = Field(ge=0, description="Number of completed runs")
    failed: int = Field(ge=0, description="Number of failed runs")

    model_config = ConfigDict(
        validate_assignment=True,
        extra="forbid",
        json_schema_extra={"example": {"pending": 2, "running": 1, "completed": 140, "failed": 7}},
    )


class RunMetrics(BaseModel):
    """Run statistics."""

    total: int = Field(ge=0, description="Total number of runs")
    by_status: RunsByStatusMetrics = Field(description="Runs grouped by status")
    success_rate: float = Field(ge=0.0, le=1.0, description="Success rate (0.0 to 1.0)")

    model_config = ConfigDict(
        validate_assignment=True,
        extra="forbid",
        json_schema_extra={
            "example": {
                "total": 150,
                "by_status": {"pending": 2, "running": 1, "completed": 140, "failed": 7},
                "success_rate": 0.933,
            }
        },
    )


class ExecutionMetrics(BaseModel):
    """Execution time statistics."""

    avg_duration_seconds: float = Field(ge=0.0, description="Average execution duration in seconds")
    total_steps_executed: int = Field(ge=0, description="Total number of steps executed")

    model_config = ConfigDict(
        validate_assignment=True,
        extra="forbid",
        json_schema_extra={"example": {"avg_duration_seconds": 1.2, "total_steps_executed": 450}},
    )


class ToolMetrics(BaseModel):
    """Tool usage statistics."""

    total_executions: int = Field(ge=0, description="Total number of tool executions")
    by_tool: dict[str, int] = Field(description="Tool execution counts by tool name")

    model_config = ConfigDict(
        validate_assignment=True,
        extra="forbid",
        json_schema_extra={"example": {"total_executions": 450, "by_tool": {"calculator": 250, "todo_store": 200}}},
    )


class MetricsResponse(BaseModel):
    """Complete metrics response."""

    timestamp: datetime = Field(description="Metrics collection timestamp (UTC)")
    runs: RunMetrics = Field(description="Run statistics")
    execution: ExecutionMetrics = Field(description="Execution statistics")
    tools: ToolMetrics = Field(description="Tool usage statistics")
    planner: PlannerMetrics = Field(description="Planner performance and reliability statistics")

    model_config = ConfigDict(
        validate_assignment=True,
        extra="forbid",
        json_schema_extra={
            "example": {
                "timestamp": "2025-01-29T10:00:00.000Z",
                "runs": {
                    "total": 150,
                    "by_status": {"pending": 2, "running": 1, "completed": 140, "failed": 7},
                    "success_rate": 0.933,
                },
                "execution": {"avg_duration_seconds": 1.2, "total_steps_executed": 450},
                "tools": {"total_executions": 450, "by_tool": {"calculator": 250, "todo_store": 200}},
                "planner": {
                    "total_plans_generated": 150,
                    "llm_plans": 120,
                    "pattern_plans": 20,
                    "cached_plans": 10,
                    "fallback_rate": 0.133,
                    "avg_tokens_per_plan": 250.5,
                    "avg_latency_ms": 450.2,
                    "cache_hit_rate": 0.067,
                },
            }
        },
    )
